language: c
env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=ON
  matrix:
    - ARCH=x86
    - ARCH=x86_64

install: |
  sudo apt-get update -qq
  sudo apt-get install -y cmake yasm
  if [ $ARCH = x86 ]; then
    sudo apt-get install -y gcc-multilib g++-multilib
  fi
before_script:
  - cmake . -DSUBHOOK_FORCE_32BIT=`([ $ARCH = x86 ] && echo 'ON') || echo 'OFF'`
script:
  - make
  - make test
