language: c

os:
  - linux
  - osx
env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=ON
  matrix:
    - ARCH=x86
    - ARCH=x86_64
addons:
  apt:
    packages:
      - gcc-multilib
      - cmake
      - yasm
  brew:
    packages:
      - cmake
      - yasm

before_script:
  - cmake . -DSUBHOOK_FORCE_32BIT=`([ $ARCH = x86 ] && echo 'ON') || echo 'OFF'`
script:
  - make
  - make test
